### PR TITLE
Ben/gbif registry

### LINKED ISSUE #6144: DWCA files can't be ingested by GBIF
This is blocking #5600 

A number of sites have been tested against api.gbif-uat.org:

- https://www.gbif-uat.org/dataset/e08de352-9383-48b0-88ae-be15cce386c5
- https://www.gbif-uat.org/dataset/503274e1-5bdc-421c-aa98-c2fecace28ce
- https://www.gbif-uat.org/dataset/370298ae-494c-485c-9a74-19d46578aa98
- https://www.gbif-uat.org/dataset/c3ca874e-ba94-4801-9e73-6e5b49cb9edd
- https://www.gbif-uat.org/dataset/306af523-20d5-48b4-a0f0-c67682cbec0b

Metadata descriptions were added in https://github.com/NaturalHistoryMuseum/scratchpads2/pull/6142, but these descriptions are not being added to the actual dwca files, which is where they're actually required.

In addition, there are other errors such as duplicate terms in metadata files

The following information has been provided by GBIF support contact Marie Grosjean:

> Hi Paul,
> 
> Thanks for these links!
> 
> I checked them and noticed that the Darwin Core Archives couldn’t be ingested by our system. The problem has to do with duplicate terms in the meta.xml file (see example in attached screenshot). This is the case for the image extension and the reference extension. I noticed by running some archives by our validator: https://www.gbif.org/tools/data-validator/1580460392697. You are very welcome to use it as well: https://www.gbif.org/tools/data-validator.
> 
> I also notice that the descriptions weren’t updated in the archives (in the eml.xml files). This is not very intuitive but the content of the EML overwrites the dataset’s metadata after a successful ingestion. This means that the updates you made for the descriptions would have disappeared if the archives were ingested. In other words, anything concerning the datasets metadata should be handled in the archives (specifically the EMLs).
> 
> The API can be used for other functions:
> 
>   -  registering a dataset,
>   -  adding or updating an endpoint,
>   -  triggering an ingestion,
>   -  updating the description of and organization or installation.
> 
> Does it make sense?
> 
> I know that our API documentation on data publishing is not always very clear. Let me know if you 
> have any question. You can also add me on Skype for quick questions or a brief chat: <skype link redacted>
> 
> Cheers
> 
> Marie
> example_issue_metaXML

(NB: GBIF login details for using the validator are stored in [Vault](https://man-vault-2.nhm.ac.uk:8200/ui/vault/secrets/scratchpads/show/GBIF%20login))

### PR DESCRIPTION
**Pull request by benscott**
Fixes #6144 - Adds EML description field and removed duplicate http://purl.org/dc/terms/identifier fields.

### CODE REVIEW

**Comment by Archilegt** [comment]
Wonderful! Many thanks, Ben!

**Comment by benscott** [comment]
You're very welcome! This fix is being released next week, and we'll then run your site against the GBIF UAT endpoint to test everything works correctly.  All being well we'll then reactivate the live submission to GBIF and your data should start flowing across again.

**Comment by timrobertson100** [comment]
Thanks Ben!

Please remember that for GBIF all we really need is the URL to the DwC-A and while the number of datasets is low (which is is) we can manually register the dataset as well.

**Comment by benscott** [comment]
Great, thanks Tim! URL of the DwC-A is myriatrix.myspecies.info/gbif-dwca.zip

**Pull request merged**
